name: ronip
description: Personal website.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  go_router: ^12.1.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/photos/

  fonts:
    - family: Inkburrow
      fonts:
        - asset: assets/fonts/inkburrow.ttf
