name: ronip
description: Personal website.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/images/icon/background.png" 
  adaptive_icon_foreground: "assets/images/icon/icon.png" 
  web:
    generate: true
    image_path: "assets/images/logos/logo-shadow.png"
    background_color: "#040C19"
    theme_color: "#040C19"
  windows:
    generate: true
    image_path: "assets/images/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/photos/

  fonts:
    - family: Inkburrow
      fonts:
        - asset: assets/fonts/inkburrow.ttf
